# Set update schedule for GitHub Actions to check they are up to date
# If one of the github actions is out of date, dependabot will open a
# PR to update the version of that action

version: 2
updates:
  # Maintain the requirements in the github actiuons
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "monthly"
    assignees:
      - dachengx
  # Maintain the requirements requirements folder
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      # Check for updates to requirements every week
      interval: "daily"
    # Raise pull requests for version updates
    # to pip against the `develop` branch
    target-branch: "master"
    assignees:
      - dachengx
