# Setup file for read the docs for python 3.8
# See https://readthedocs.org/projects/docs/downloads/pdf/stable/
version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"

sphinx:
  configuration: docs/conf.py

python:
  # Install our python package before building the docs
  # NB, this is not the default path for sphinx builds
  install:
  - requirements: extra_requirements/requirements-tests.txt
  - method: pip
    path: .

formats:
  - pdf
  - epub
