# .readthedocs.yml

# Required
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  image: latest

python:
  version: "3.8"
  install:
    - requirements: extra_requirements/requirements-tests.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .

formats:
  - pdf
  - epub
