# .readthedocs.yml

# Required
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  version: "3.9"
  install:
    - requirements: extra_requirements/requirements-tests.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
    - method: setuptools
      path: .

formats:
  - htmlzip
  - epub
