# .readthedocs.yml

# Required
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
    image: latest

python:
    version: 3.6
    install:
      - method: pip
        path: .
        extra_requirements:
           - docs
      - method: setuptools
        path: .
