# Add a coverage file to the PR on request (must be manually triggered on github actions)
name: Build coverage file

# Trigger this only when requested
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install strax
        run: |
            git clone https://github.com/AxFoundation/strax.git ../strax
            pip install ../strax
      - name: Install python dependencies
        uses: py-actions/py-dependency-install@v2
      - name: Install straxen
        run: bash .github/scripts/install_straxen.sh
      - name: Install pytest and hypothesis etc
        run: pip install pytest hypothesis flake8 pytest-cov boltons tensorflow
      - name: Build coverage file
        run: |
            pytest --cache-clear --cov=straxen > pytest-coverage.txt
      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2
      - name: goodbye
        run: echo goodbye
