on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
  push:
    branches:
      - master

name: Coveralls

jobs:

  build:
    name: Coveralls
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v2 # https://github.com/marketplace/actions/setup-miniconda
      with:
        python-version: 3.8
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install requirements for tests and latest strax
      run: |
        pip install -r extra_requirements/requirements-tests.txt
        pip install git+https://github.com/AxFoundation/strax.git
    - name: patch utilix file
      run: bash .github/scripts/create_readonly_utilix_config.sh
      env:
        # Database
        RUNDB_API_URL: ${{ secrets.RUNDB_API_URL }}
        RUNDB_API_USER_READONLY: ${{ secrets.RUNDB_API_USER_READONLY }}
        RUNDB_API_PASSWORD_READONLY: ${{ secrets.RUNDB_API_PASSWORD_READONLY}}
        PYMONGO_URL: ${{ secrets.PYMONGO_URL }}
        PYMONGO_USER: ${{ secrets.PYMONGO_USER }}
        PYMONGO_PASSWORD: ${{ secrets.PYMONGO_PASSWORD }}
        PYMONGO_DATABASE: ${{ secrets.PYMONGO_DATABASE }}
        # SCADA
        SCADA_URL: ${{ secrets.SCADA_URL }}
        SCADA_VALUE_URL: ${{ secrets.SCADA_VALUE_URL }}
        SCADA_USER: ${{ secrets.SCADA_USER }}
        SCADA_LOGIN_URL: ${{ secrets.SCADA_LOGIN_URL }}
        SCADA_PWD: ${{ secrets.SCADA_PWD }}
    - name: Create pre-apply function file
      # In case we do not have database. We need to make a local file for
      # The pre_apply_function (see #559)
      env:
        HAVE_ACCESS_TO_SECTETS: ${{ secrets.RUNDB_API_URL }}
      if: env.HAVE_ACCESS_TO_SECTETS == null
      run: |
        bash .github/scripts/create_pre_apply_function.sh $HOME
    - name: Coveralls
      env:
        NUMBA_DISABLE_JIT: 1
      run: |
        coverage run --source=straxen setup.py test -v
    - name: Upload coverage
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      if: env.COVERALLS_REPO_TOKEN != null
      run: |
         coveralls
